spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:${PORT}/springbootjpa"
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}