server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password:
    url: jdbc:postgresql://localhost:5432/fantastic-restaurants
    username:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: mail_user
    password: mail_password

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000